site_name: bakelite
site_description: Bakelite is a utility that makes it simple to communicate with your firmware.
site_author: Brendan Powers

repo_url: https://github.com/brendan0powers/bakelite
edit_uri: https://github.com/brendan0powers/bakelite/edit/master/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  # - Tutorial: tutorial.md
  - Protocol Spec: protocol.md
  # - Languages:
  #   - C++ (Tiny): cpptiny.md
  #   - Python: python.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
