site_name: bakelite
site_description: bakelite project description
site_author: Brendan Powers

repo_url: https://github.com/brendan0powers/bakelite
edit_uri: https://github.com/brendan0powers/bakelite/edit/master/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Protocol Spec: protocol.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
